Add normalization function for DuplicateKeyTracker
JupiterOne/sdk pull request #358
Opened 2020-10-16 20:20 UTC by ndowmon

The azure integration has been hitting some issues where entity `id`s are returned with inconsistent casing. This makes the `findEntity` function useless in most cases, and prohibits us from identifying valid relationships across an environment. This PR allows users to pass a `keyNormalizationFunction` into an `InvocationConfig` that transforms keys before storing them (or retrieving them from) the `DuplicateKeyTracker`.

2020-10-17 13:56 UTC, austinkelleher approved these changes
Nice. This seems like a good approach. 👍

2020-10-18 15:15 UTC, aiwilliams requested changes

2020-10-19 13:25 UTC, ndowmon commented on packages/integration-sdk-core/src/types/config.ts
> +  keyNormalizationFunction?: KeyNormalizationFunction;
That works. I can change the parameter name but leave the type as `type KeyNormalizationFunction` (I don't think `type NormalizeGraphObjectKey` is a good description for a type, what do you think?)

2020-10-19 13:46 UTC, ndowmon commented
Also merged https://github.com/JupiterOne/sdk/pull/359 into this PR.

2020-10-19 13:49 UTC, aiwilliams commented on packages/integration-sdk-core/src/types/config.ts
> +  keyNormalizationFunction?: KeyNormalizationFunction;
I think `KeyNormalizationFunction` is perfect! Thanks for the variable rename.

2020-10-19 14:03 UTC, aiwilliams approved these changes

2020-10-19 14:26 UTC, merged