Add `mutations` export from recording.ts
JupiterOne/sdk pull request #401
Opened 2020-12-18 21:46 UTC by ndowmon

A number of integrations receive gzipped responses from provider APIs. As a convention, we prefer to unzip responses so that responses can be reviewed for sensitive information before publishing in open-source projects.

2020-12-18 22:45 UTC, austinkelleher requested changes

2020-12-18 22:45 UTC, austinkelleher commented on packages/integration-sdk-testing/package.json
> +    "zlib": "^1.0.5"
zlib is actually a native module. Don't install a 3rd party package for it.

2020-12-23 16:56 UTC, aiwilliams submitted a review, later dismissed
Cool, glad to see this moving to a reusable location now that it's proven to function across a few!

2020-12-23 21:23 UTC, austinkelleher approved these changes

2020-12-23 21:26 UTC, aiwilliams approved these changes

2020-12-31 14:41 UTC, merged