Gzip Requests
JupiterOne/sdk pull request #982
Opened 2023-10-16 17:35 UTC by zemberdotnet

# Description

Compress data sent

2023-10-18 16:08 UTC, maxheckel requested changes

2023-10-18 16:09 UTC, maxheckel commented on packages/integration-sdk-cli/src/__tests__/util/synchronization.ts
> +      if (req.hasHeader('Content-Encoding')) {
I'm dumb, just noticed this was in the tests.  Not as important to do this.

2023-10-19 13:50 UTC, zemberdotnet commented on packages/integration-sdk-runtime/package.json
> -    "axios": "^0.27.0",
Now a direct dependency of @lifeomic/alpha

2023-10-19 16:44 UTC, maxheckel approved these changes

2023-10-19 17:04 UTC, merged